name: deploy

on:
  push:
    branches: ['main']

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deliver-container:
    runs-on: ubuntu-latest
    steps:
      - id: deploy-docker
        name: Deploy container to ${{ secrets.TARGET_HOST }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_HOST_SSH_USERNAME }}
          key: ${{ secrets.TARGET_HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.TARGET_HOST_SSH_USERNAME }}/bstu-edx \
            && (git -C ${{ env.REPO_NAME }} pull || git clone https://github.com/${{ github.repository }} ${{ env.REPO_NAME }}) \
            && cd ${{ env.REPO_NAME }} && docker-compose build && docker-compose up -d


  
